#!/usr/bin/env python3
import tempfile, os, subprocess, sys, json

# Load the freshly built dashboard data
dash = json.load(open(r"C:\Users\robby\Downloads\Hermes Drive\AI News Dashboard\data\latest.json", encoding="utf-8"))
stories = dash["stories"]

def tag_html(tags):
    out = ""
    colors = {
        "LLMs": "#4f8cff", "Vision": "#b06bff", "Open Source": "#26c281",
        "Research": "#ffb020", "Agents": "#ff6b9d", "Industry": "#00b8d9",
        "Regulation": "#ff5c5c", "Hardware": "#8c54ff", "Tools": "#2ec4b6", "News": "#8893a5",
    }
    for t in tags:
        c = colors.get(t, "#8893a5")
        out += f'<span style="background:{c};color:#fff;padding:2px 8px;border-radius:10px;font-size:11px;margin-right:4px;display:inline-block;">{t}</span>'
    return out

rows = ""
for i, s in enumerate(stories, 1):
    rows += f"""
    <tr>
      <td style="padding:14px 16px;border-bottom:1px solid #243049;vertical-align:top;">
        <div style="font-size:13px;color:#7c8aa5;margin-bottom:4px;">#{i} &middot; {s['source']} &middot; {s['date']} &middot; &#9650; {s['upvotes']} &middot; &#128172; {s['comments']}</div>
        <div style="font-size:16px;font-weight:600;color:#eaf0ff;margin-bottom:6px;line-height:1.3;">
          <a href="{s['url']}" style="color:#eaf0ff;text-decoration:none;">{s['title']}</a>
        </div>
        <div style="font-size:13px;color:#aeb9cf;line-height:1.5;margin-bottom:8px;">{s['summary']}</div>
        <div>{tag_html(s['tags'])}</div>
      </td>
    </tr>
    """

html = f"""<!DOCTYPE html>
<html lang="en">
<body style="margin:0;padding:0;background:#0f1320;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#0f1320;">
    <tr><td align="center" style="padding:24px 12px;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#141a2b;border-radius:14px;overflow:hidden;box-shadow:0 8px 30px rgba(0,0,0,0.4);">
        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);padding:28px 24px;">
            <div style="font-size:24px;font-weight:700;color:#ffffff;">&#128220; AI News Dashboard</div>
            <div style="font-size:14px;color:#9fb0d0;margin-top:6px;">{dash['generated_at']}</div>
          </td>
        </tr>
        <!-- Stats -->
        <tr>
          <td style="padding:18px 24px;background:#101626;border-bottom:1px solid #243049;">
            <span style="display:inline-block;background:#1f2940;color:#cdd8ee;padding:6px 12px;border-radius:8px;font-size:13px;margin-right:8px;">&#128172; Reddit threads: {dash['stats']['reddit_threads']}</span>
            <span style="display:inline-block;background:#1f2940;color:#cdd8ee;padding:6px 12px;border-radius:8px;font-size:13px;margin-right:8px;">&#128240; Articles scanned: {dash['stats']['articles_scanned']}</span>
            <span style="display:inline-block;background:#1f2940;color:#cdd8ee;padding:6px 12px;border-radius:8px;font-size:13px;">&#128293; Subreddits: {dash['stats']['subreddits_scanned']}</span>
          </td>
        </tr>
        <!-- Stories -->
        <tr>
          <td style="padding:0;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0">{rows}</table>
          </td>
        </tr>
        <!-- Note -->
        <tr>
          <td style="padding:16px 24px;background:#101626;font-size:12px;color:#6f7d99;line-height:1.5;border-top:1px solid #243049;">
            Note: Reddit API and the Firecrawl web-search backend were unavailable today (search backend returned HTTP 402 / insufficient credits). Stories were sourced from the Hacker News AI-filtered feed.
          </td>
        </tr>
        <!-- Footer -->
        <tr>
          <td style="padding:18px 24px;background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);font-size:12px;color:#8c9ab5;text-align:center;">
            Generated by Hermes Agent &#129302;
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>
"""

tmp = os.path.join(tempfile.gettempdir(), '836dcdb6b75f_report.html')
with open(tmp, 'w', encoding='utf-8') as f:
    f.write(html)

gws = os.path.expanduser('~/AppData/Local/hermes/skills/productivity/google-workspace/scripts/google_api.py')
result = subprocess.run([
    sys.executable, gws, 'gmail', 'send',
    '--to', 'snowflake.and.you@gmail.com',
    '--subject', '🗞️ AI News Dashboard — ' + __import__('datetime').date.today().isoformat(),
    '--html-file', tmp,
    '--html'
], capture_output=True, text=True)

print(result.stdout)
if result.stderr:
    print('STDERR:', result.stderr)
os.unlink(tmp)
